### PR TITLE
DOC: updates readme for scipy conference

### PR DESCRIPTION
**Pull request by deniederhut**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Some of these are a bit old. I'd like to at least get pandas, dask, and NumPy on their latest versions. I'll run through the materials now with the latest.

Do we have a preference for jupyterlab vs. notebook?

**Comment by deniederhut** [comment]
No worries! If we're modifying the dependencies, it might be nice to trim them down a bit, and make them less strict (e.g. numpy >= 1.9.0) where we can.

I haven't used Jupyterlab yet, but it looks fun and I'd be down to give it a whirl

**Comment by TomAugspurger** [comment]
The main issue I've had with J-lab is that it doesn't provide jquery like
the notebook, so the formatted cells with the exercise headers will have to
be modified.

I have a slight preference for creating a new environment and pinning exact
dependencies, just to minimize cross-version incompatibilities.
@jorisvandenbossche do you have thoughts?


On Sun, Jun 17, 2018 at 10:00 PM, Dillon Niederhut <notifications@github.com

**Comment by jorisvandenbossche** [comment]
> The main issue I've had with J-lab is that it doesn't provide jquery like the notebook, so the formatted cells with the exercise headers will have to be modified.

For that reason I am for now still using the notebook (and not jupyterlab) for tutorials. There are also some other packages that do not yet fully work in jupyterlab (like matplotlib interactive notebook)

> I have a slight preference for creating a new environment and pinning exact dependencies

No strong preference here, having minimum versions (even when it is the latest) is fine for me as well. 
But if we go for new environment, I think we should more strongly recommend conda.

**Comment by TomAugspurger** [comment]
Of course, I haven't found time to actually update things, so happy to
merge whatever is required for the organizers :)

**Comment by deniederhut** [comment]
Haha okay, we'll merge this now, but I would keep in mind that the odds anyone does their installation for the tutorial three weeks in advance is essentially 0%. There is still time to tinker with the instructions and dependencies.

**Pull request merged**
